export 'package:the_life_water/presentation/screen/admin_screen/orders/orders_screen.dart';
export 'package:the_life_water/presentation/screen/admin_screen/add_new_buy_router/add_new_buy_to_client_screen.dart';
export 'package:the_life_water/presentation/screen/admin_screen/create_new_client/create_new_client_screen.dart';
export 'package:the_life_water/presentation/screen/admin_screen/product/product_screen.dart';
export 'package:the_life_water/presentation/screen/admin_screen/generation_inf/generation_info_screen.dart';
export 'package:the_life_water/presentation/screen/admin_screen/watch_client/watch_client_screen.dart';
export 'package:the_life_water/presentation/screen/testingScreen/testingScreen.dart';
export 'package:the_life_water/presentation/screen/admin_screen/admin_screen.dart';
export 'package:the_life_water/presentation/screen/router_screen/router_screen.dart';
